
import clases.imagenfondo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jacky
 */
public class FilmMagic extends javax.swing.JFrame {

    /**
     * Creates new form FilmMagic
     */
    private Registro NuevaVentana;//se declaran variables para la visibilidad de los JinternalFran
    private Modificacion ventana;
    private Eliminacion ventana2;
    private catalogo ventana3;
   

    public FilmMagic() {
        initComponents();
        jDesktopPane1.setBorder(new imagenfondo());
        this.setExtendedState(FilmMagic.MAXIMIZED_BOTH);//Se puso una imagen de Fondo en el JDesktopPane
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Registrocliente = new javax.swing.JMenuItem();
        ModificacionC = new javax.swing.JMenuItem();
        EliminarCuenta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        IngresoalCatalogo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SalirPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 0));

        jMenu1.setBackground(new java.awt.Color(0, 255, 204));
        jMenu1.setText("Membresia");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        Registrocliente.setText("Obtener Membresia");
        Registrocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroclienteActionPerformed(evt);
            }
        });
        jMenu1.add(Registrocliente);

        ModificacionC.setText("Modificar tu cuenta");
        ModificacionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificacionCActionPerformed(evt);
            }
        });
        jMenu1.add(ModificacionC);

        EliminarCuenta.setText("Eliminar cuenta");
        EliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCuentaActionPerformed(evt);
            }
        });
        jMenu1.add(EliminarCuenta);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(51, 255, 204));
        jMenu2.setText("Catalogo");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        IngresoalCatalogo.setText("Ingresar al catalogo");
        IngresoalCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoalCatalogoActionPerformed(evt);
            }
        });
        jMenu2.add(IngresoalCatalogo);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(204, 0, 0));
        jMenu3.setText("Salir");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        SalirPrograma.setText("Salir");
        SalirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirProgramaActionPerformed(evt);
            }
        });
        jMenu3.add(SalirPrograma);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroclienteActionPerformed
        // TODO add your handling code here:
        NuevaVentana = new Registro();
        jDesktopPane1.add(NuevaVentana);//Codigo para hacer visible JinternalFrame(Registro)
        
    }//GEN-LAST:event_RegistroclienteActionPerformed

    private void IngresoalCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoalCatalogoActionPerformed
        // TODO add your handling code here:
        ventana3 = new catalogo();
        jDesktopPane1.add(ventana3);//Codigo para hacer visible JinternalFrame(Catalogo)
    }//GEN-LAST:event_IngresoalCatalogoActionPerformed

    private void SalirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirProgramaActionPerformed
         // TODO add your handling code here:
         dispose();//Codigo  para  salir del Programa
    }//GEN-LAST:event_SalirProgramaActionPerformed

    private void ModificacionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificacionCActionPerformed
        // TODO add your handling code here:
        ventana = new Modificacion();
        jDesktopPane1.add(ventana);//Codigo para hacer visible JinternalFrame(Modificacion)
    }//GEN-LAST:event_ModificacionCActionPerformed

    private void EliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCuentaActionPerformed
        // TODO add your handling code here:
        ventana2 = new Eliminacion();
        jDesktopPane1.add(ventana2);//Codigo para hacer visible JinternalFrame(Eliminacion)
    }//GEN-LAST:event_EliminarCuentaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmMagic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmMagic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EliminarCuenta;
    private javax.swing.JMenuItem IngresoalCatalogo;
    private javax.swing.JMenuItem ModificacionC;
    private javax.swing.JMenuItem Registrocliente;
    private javax.swing.JMenuItem SalirPrograma;
    public static javax.swing.JDesktopPane jDesktopPane1;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
